### ISSUE TITLE
Are there any plans to update it to version 23.10?

### ISSUE THREAD

**Issue by castellco** [glutanimate/syntax-highlighting#46]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

Are there any plans to update it to version 23.10? This add on is the best for learning code, but it is incompatible with the latest version of Anki. Please.

**Comment by glutanimate** [comment]
Hi, yes it's on my list of add-ons to update.

**Comment by castellco** [comment]
I'm looking forward to it. Thanks!

**Comment by dluschan** [comment]
This patch should fix the issue: https://github.com/glutanimate/syntax-highlighting/pull/47

**Comment by cav71** [comment]
@glutanimate @dluschan thanks for the incredible tool ankit is. Would you consider to share the burden to maintain this repo with someone that can help?
This pull request is kind of ready to go, but hold for weeks (see[47](https://github.com/glutanimate/syntax-highlighting/pull/47)).

**Comment by Lexora** [comment]
Looking forward to running this on new version - 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
```

When loading Syntax Highlighting for Code:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/home/usr.local/share/Anki2/addons21/1463041493/__init__.py", line 15, in <module>
    from . import main
  File "/home/usr/.local/share/Anki2/addons21/1463041493/main.py", line 21, in <module>
    from .consts import *  # import addon_path
  File "/home/usr/.local/share/Anki2/addons21/1463041493/consts.py", line 22, in <module>
    addon_path = os.path.dirname(__file__).decode(sys_encoding)
AttributeError: 'str' object has no attribute 'decode'

```
Oh this looks like a quick fix, ^ can I help to create a PR if previous one is stale?

**Comment by cav71** [comment]
@Lexora I wrote a fork here [syntax-highlighting-ng](https://github.com/cav71/syntax-highlighting-ng) / [566351439](https://ankiweb.net/shared/info/566351439): it includes improvements and fixes for the newest Anki version.

**Comment by DevinCLane** [comment]
Just checking in to see if this will be updated for the newest version of anki? Great add-on here, thanks for your work

**Comment by aljab012** [comment]
> @Lexora I wrote a fork here [syntax-highlighting-ng](https://github.com/cav71/syntax-highlighting-ng) / [566351439](https://ankiweb.net/shared/info/566351439): it includes improvements and fixes for the newest Anki version.

Thanks a lot @cav71

**Comment by millan-figueroa** [comment]
Thank you for your work this add-on is perfect and very necessary! Wondering if there's a way to format the text to wrap to fit a phone screen so we don't have to scroll to see the whole code snippet! Works perfect on laptop/pc though.
